### ISSUE TITLE
Different URL to access Expert Edit Profile page

### ISSUE THREAD

**Issue by 8bitzz** [dangvuthang/COSC2769-rmit#111]
### Description
- `Expert Edit Profile` page can be accessed by either path `/edit-room/` OR `dashboard/profile`

<img width="1675" alt="Screen Shot 2021-08-27 at 15 56 54" src="https://user-images.githubusercontent.com/23531403/131112670-a1752a43-dd90-44e6-bf4e-f6258bdae591.png">

<img width="1675" alt="Screen Shot 2021-08-27 at 15 57 13" src="https://user-images.githubusercontent.com/23531403/131112707-9deeb3a8-4a42-4eb3-ae86-dee3292487d9.png">

- Should we use only one path for experts to edit their profile?

**Comment by ManPhamQuang** [comment]
@8bitzz the two routes are for experts and normal user. However, I forgot to remove the `description` from the user's `edit-profile` route which @dangvuthang fortunately discoverd in #113. Will work on a PR that fix this.
